### ISSUE TITLE
TGALoader.writeTGA does not seem to work(Linux)

### ISSUE THREAD

**Issue by samrat** [kosua20/PtahRenderer#1]
When I run `PtahRendererDemoOffline`, I see the following output but the rendered files are nowhere to be found:

```
./.build/debug/PtahRendererDemoOffline
Starting Ptah Renderer...
Done!
```

I'm running swift-3.1 on Arch Linux:

```
swift -v
Swift version 3.1 (swift-3.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by kosua20** [comment]
Thanks for your input!
The TGA writer was silently failing because the destination directory wasn't created in the repo. I have fixed both issues, please tell me if this works for you.

**Comment by samrat** [comment]
Thanks for the prompt response! It works for me now. By the way, is there any plan to support the online demo for Linux?

**Comment by kosua20** [comment]
Well, your question has given me the motivation to implement it! 😃 

I have added the PtahRendererDemoOpenGL module, that relies on an OpenGL 3 backend to display in real-time the output of the Ptah renderer, and handle simple user interactions.
The setup is a bit more involved than for the other modules: you need GLFW3 installed in its default location ; the other dependencies (Swift wrappers for OpenGL and GLFW3) will be downloaded by the Swift Package Manager. 

I have been able to test it under Ubuntu 16.04, don't hesitate to report any bug you encounter.

**Comment by samrat** [comment]
Worked for me, although I had to make a copy of the GLFW shared object file to get it compiling. Thanks, I will close the issue now.
